### ISSUE TITLE
Resolving dependencies under CentOS 7

### ISSUE THREAD

**Issue by Bifrozt** [sookyp/honeyd-python#1]
Hi @sookyp 

Thanks for starting this awesome imitative! :+1: 

I'm trying to resolve the dependencies on CentOS 7 with the provided command in the README 
```
yum -y install git farpd mysql-server mysql-devel python-devel python-setuptools MYSQLdb-python libpcap-dev tkinter tk-devel
```
This returned a few `No package` messages
```
No package farpd available.
No package mysql-server available.
No package MYSQLdb-python available.
No package libpcap-dev available.
```
It might be that we can resolve this if
- `libpcap-dev` should be replaced with **`libpcap-devel`** 
- `MYSQLdb-python` should be replaced with **`MySQL-python`**

Installing `mysql-server` on CentOS 7 don´t appears to be part of their default repo (really??) but, it can be installed from their community repo. There's a suggestion to how this can be done in **[this article](https://www.linode.com/docs/databases/mysql/how-to-install-mysql-on-centos-7#install-mysql)**.

The process of installing `mysql-server` on CentOS 7 looks like this:
```
wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm
sudo rpm -ivh mysql-community-release-el7-5.noarch.rpm
yum update
```

---

I think all the dependencies should have been resolved under CentOS 7 so far, all except one: **`farpd`**.
When you installed `farpd` under CentOS 7, how did you do this and what repo did you find it in?

---

Not including the installation of the `mysql-server` and `farpd`, maybe the command for resolving dependencies under CentOS 7 should be changed to the following?
```
yum -y install git mysql-devel python-devel python-setuptools libpcap-devel MySQL-python tkinter tk-devel
```

**Comment by sookyp** [comment]
Hey @Bifrozt,

Thank you for your feedback! It seems that ``farpd`` is only supported up to CentOS 5, so for newer versions of CentOS, the network traffic has to be routed to the honeypot. I'd like to drop ``farpd`` as soon as possible and execute ARP spoofing within the honeypot. For now, I changed the ``README.md`` and ``deploy/mhn/deploy_honeyd.sh`` script to list the correct packages.

**Comment by Bifrozt** [comment]
Thanks for the quick reply.
Good to know, I'll try working around it on CentOS 7.
If I make it work properly, I might try using your project instead of the original one.
Truly hope you continue development of this project.
