### ISSUE TITLE
Netmask is not used with subnet on gre tunnel interface

### ISSUE THREAD

**Issue by standa4** [sookyp/honeyd-python#3]
It looks like that the creation of the gre tunnel does not use the netmask for the subnet from the honeyd.cfg file (line subnet = ... in [tunnel] section). The used netmask is /32 so the other end of the tunnel is not reachable. Connection works after editing the ip addres and and netmask of the interface manually.

**Comment by sookyp** [comment]
Hello @standa4, added the missing netmask configuration in 0aa10c6, should be fixed now.

**Comment by standa4** [comment]
Thank you for your response.
The problem was fixed.
